# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
target 'HandyCo' do
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'HandyCoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HandyCo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HandyCo-tvOS

  target 'HandyCo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
